### ISSUE TITLE
Missing "1.16.0 | Nether Update" info on Releases page

### ISSUE THREAD

**Issue by NetLightDev** [ZtechNetwork/MCBVanillaBehaviorPack#3]
The "Releases" page does not contain any documentation about "1.16.0 | Nether Update" Vanilla Behavior Pack changes
(as well as the pack file itself is missing).

Currently, the detailed information about "1.16.0 | Nether Update" is stored in README.md, however from what is declared there
("From v1.16 and on, changelogs shown here will only go back two major versions to prevent a long list. ")
one may conclude that at some time the documentation about "1.16.0 | Nether Update" will be removed from README.md.

If the "Releases" page is assumed to contain the full history, then the documentation about "1.16.0 | Nether Update" should be included there. Otherwise, an important part of history info will be lost (when removed from README.md).

**Comment by LeronHinds** [comment]
Information on v1.16.0 was left out due to time I updated the repository. By the time I came around to 1.16 I've already missed the initial release and I just added information on the version v1.16.20 and up from that point. I'm not always available to update to update this repository so whatever the latest version is at time I get around to it is what I'll provide in the [releases](https://github.com/ZtechNetwork/MCBVanillaBehaviorPack/releases) page. Considering users will be referencing to the latest version of the behavior pack, there is no need for me to go back to a previous version as the latest would cover that and whatever's new currently. If needed you can refer to the official changelog [here](https://feedback.minecraft.net/hc/en-us/articles/360044928311-Minecraft-Nether-Update-1-16-0-Bedrock-). I apologize for the inconvenience.
